-- DML : DELETE

CREATE TABLE EMP_TEMP2
    AS SELECT * FROM EMP;
    
SELECT * FROM EMP_TEMP2;

-- DELETE 문법
-- DELETE FROM 테이블명
-- (WHERE) 삭제할 대상 행을 선별하기 위한 조건식;

DELETE FROM EMP_TEMP2
WHERE JOB = 'MANAGER';

SELECT * FROM EMP_TEMP2;

-- 서브쿼리문 사용하기
DELETE FROM EMP_TEMP2
WHERE EMPNO IN(SELECT EMPNO 
                FROM EMP_TEMP2 E, SALGRADE S
                WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                AND DEPTNO = 30
                AND S.GRADE = 3);
SELECT * FROM EMP_TEMP2;

SELECT EMPNO 
FROM EMP_TEMP2 E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
    AND DEPTNO = 30
    AND S.GRADE = 3;
    
-- 테이블 전체 데이터 삭제하기
DELETE FROM EMP_TEMP2;