-- DML UPDATE 데이터 수정

CREATE TABLE DEPT_TEMP2
    AS SELECT * FROM DEPT;
    
SELECT * FROM DEPT_TEMP2;

-- UPDATE문의 문법
-- UPDATE [테이블]
-- SET [변경할 열1] = [변경할 값1],[변경할 열 2] = [변경할 값2], ....
-- WHERE 변경할 대상을 선별하는 조건

UPDATE DEPT_TEMP2
SET LOC='SEOUL';
-- 조건절을 주지 않을 경우 선택한 열의 모든 데이터가 수정된다.
SELECT * FROM DEPT_TEMP2;
-- 수정한 내용을 되돌리고 싶을 때;
ROLLBACK; -- TCL

UPDATE DEPT_TEMP2
SET LOC='SEOUL'
WHERE DEPTNO=40;
SELECT * FROM DEPT_TEMP2;

-- 서브쿼리 사용하기
SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40;

UPDATE DEPT_TEMP2
SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40)
WHERE DEPTNO = 40;

SELECT * FROM DEPT_TEMP2;

-- WHERE 절에서 사용하는 방법
UPDATE DEPT_TEMP2
SET LOC = 'SEOUL'
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME='OPERATIONS');

SELECT * FROM DEPT_TEMP2;

SELECT DEPTNO FROM DEPT_TEMP2 WHERE DNAME='OPERATIONS';
-- UPDATE문에서 서브쿼리를 사용할 때 주의점
-- 꼭 SELECT문으로 한번 확인하고, UPDATE문으로 작성할 것.